config/routes.rb
Web::Application.routes.draw do

  root :action => :index, :controller => :polyhoraire

  namespace :polyhoraire do
    root :action => :index
    post 'connect'
    get 'trimesters'
    namespace :export do
      root :action => :index
      namespace :google do
        get 'oauth2callback'
        get 'calendars'
        match 'export/:trimester' => '#export'
        get 'export'
        match 'pushto/:calendarID' => '#pushto'
        get 'pushto'
        
        root :action => :index
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polyhoraire/export/google_controller.rb
#encoding: UTF-8

require 'polyhoraire'
require 'google_exporter'


class Polyhoraire::Export::GoogleController < ApplicationController
  Poly::userConfDir = 'config'
  before_filter :auth
  
  def export
    redirect_to :action => :calendars
  end
  
  def index
    redirect_to :action => :calendars
  end
  
  def pushto
    auth = Poly::Auth.new
    auth.connect(session[:user],session[:password],session[:bday])
    
    schedule = Poly::Schedule.new(auth,session[:trimester].to_i)
    
    begin
      @exporter.send(schedule,params[:calendarID])
    rescue ClientError
      @error = 'Problème du côté du serveur'
    rescue ServerError
      @error = 'Problème du côté de google'
    rescue TransmissionError
      @error = 'Problème de transmission des données'
    end
    
  end
  
  def calendars
    @calendarList = @exporter.calendarList
    puts @calendarList
  end
  
  def oauth2callback
    session[:tokenPair] = @exporter.newTokenPair.to_hash
    redirect_to :action => :calendars
  end
  
  private
  
  def auth
    session[:trimester] = params[:trimester] if params[:trimester]
    @exporter = GoogleExporter.new
    callBackURI = url_for :action => :oauth2callback, :id => nil
    
    tokenPair = TokenPair.new(session[:tokenPair])
    
    accessToken = @exporter.authWeb(params[:code],callBackURI,tokenPair)
    unless accessToken || params[:action] == 'oauth2callback'
      flash[:trimester] = params[:trimester]
      redirect_to @exporter.authURI
    end
  end
end

app/controllers/polyhoraire/export_controller.rb
require 'polyhoraire'

class Polyhoraire::ExportController < ApplicationController
  before_filter :polyFetch

  def initialize
    @exporters = {
      'google' => 'Google Calendar'  
    }
  end  
  
  private 
  
  def polyFetch
    @auth = Poly::Auth.new
    @auth.connect(session[:user],session[:password],session[:bday])
  end
end

app/controllers/polyhoraire_controller.rb
require 'polyhoraire/auth'
require 'polyhoraire/schedule'
require 'google_exporter'

class PolyhoraireController < ApplicationController
  
  def index
    
  end
  
  def connect
    auth = Poly::Auth.new
    begin
      auth.connect(params[:user],params[:password],params[:bday])
      
      session[:user] = params[:user]
      session[:password] = params[:password]
      session[:bday] = params[:bday]
      
      session[:trimesters] = auth.trimesters
      
      redirect_to :action => :trimesters
    rescue
      redirect_to :action => :index
    end
  end
  
  def trimesters
    
    auth = Poly::Auth.new
    begin
      auth.connect(session[:user],session[:password],session[:bday])
    rescue
      redirect_to :action => :index
    end
    
    @trimesters = auth.trimesters
  end
  
  
  private 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polyhoraire/exporter/google_helper.rb
module Polyhoraire::Exporter::GoogleHelper
end

app/helpers/polyhoraire/exporter_helper.rb
module Polyhoraire::ExporterHelper
end

app/helpers/polyhoraire_helper.rb
module PolyhoraireHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/polyhoraire/export.html.erb
<h1>Polyhoraire#export</h1>
<p>Find me in app/views/polyhoraire/export.html.erb</p>

app/views/polyhoraire/export/google/calendars.html.erb
<% @calendarList.each do |id, name| %>
	<li>
		<span class="calendarColor" style="background-color: #"></span>
		<a href="<%=  url_for :controller => 'polyhoraire/export/google',:action => 'pushto', :calendarID => id%>"><%= name %></a>
	</li>
<% end %>

app/views/polyhoraire/export/google/pushto.html.erb
<% if @error %>
	<h2>Une erreur est survenue</h2>
	<p><%= @error %></p>
<% else %>
	<h2>Réussite !</h2>
	<p>Vous être maintenant prêt a contempler votre compte Google Calendar</p>
<% end %>

app/views/polyhoraire/export/show.html.erb
<% @exporters.each do |exporterID, name|%>
	<li><a href="<%= polyhoraire_export_path + '/' + exporterID  + '/' + params[:trimester]%>"><%= name %></a></li>
<% end %>

app/views/polyhoraire/index.html.erb
<%= form_tag(url_for(:action => 'connect'), :method => 'post') do%>
	<%= label_tag(:user, "Nom d'utilisateur : ")%>
	<%= text_field_tag(:user) %>
	<%= label_tag(:password, "Mot de passe : ")%>
	<%= password_field_tag(:password)%>
	<%= label_tag(:bday,"Date de naissance : ")%>
	<%= text_field_tag(:bday)%>
	
	<%= submit_tag("Se connecter")%>
<% end %>

app/views/polyhoraire/results.html.erb
<h1>Polyhoraire#results</h1>
<p>Find me in app/views/polyhoraire/results.html.erb</p>

app/views/polyhoraire/trimesters.html.erb
<% @trimesters.each do |id, name|%>
	<li>
		<a href="<%= url_for(:controller => 'polyhoraire/export/google', :action => :export, :trimester => id) %>"><%= name %></a>
	</li>
	
<% end%>